### ISSUE TITLE
Bazel HTTP Archive Needs Update

### ISSUE THREAD

**Issue by ryanaveo** [realm/SwiftLint#4051]
### New Issue Checklist

- [ x ] Updated SwiftLint to the latest version
- [ x ] I searched for [existing GitHub issues](https://github.com/realm/SwiftLint/issues)

### Describe the bug

The URL of the HTTP Archive for SwiftLint points to an older version that uses the old `com_github_realm_swiftlint` workspace name. A new version needs to be uploaded with these changes: https://sourcegraph.com/github.com/realm/SwiftLint/-/commit/77a219d24ebf56d2b3638014d9aa37772854db94?visible=3

##### Complete output when running SwiftLint, including the stack trace and command used

`./bazelw run -c opt @SwiftLint//:swiftlint`

```
ERROR: An error occurred during the fetch of repository 'swiftlint_com_github_scottrhoyt_swifty_text_table':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ios/external/bazel_tools/tools/build_defs/repo/http.bzl", line 110, column 28, in _http_archive_impl
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_ios/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, column 41, in workspace_and_buildfile
		ctx.file("BUILD.bazel", ctx.read(ctx.attr.build_file))
Error in read: Unable to load package for @com_github_realm_swiftlint//bazel:SwiftyTextTable.BUILD: The repository '@com_github_realm_swiftlint' could not be resolved: Repository '@com_github_realm_swiftlint' is not defined
ERROR: /Users/raveo/Uber/ios/WORKSPACE:52:16: fetching http_archive rule //external:swiftlint_com_github_scottrhoyt_swifty_text_table: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_ios/external/bazel_tools/tools/build_defs/repo/http.bzl", line 110, column 28, in _http_archive_impl
		workspace_and_buildfile(ctx)
	File "/private/var/tmp/_bazel_ios/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 61, column 41, in workspace_and_buildfile
		ctx.file("BUILD.bazel", ctx.read(ctx.attr.build_file))
```

### Environment

* SwiftLint version: 0.47.1
* Installation method used: source

**Comment by jpsim** [comment]
Thanks, it was pointing to the commit from the PR that introduced support for it, and of course that branch is now gone. Fixed in #4052.
