### ISSUE TITLE
The rule 'SwiftLint:legacy_constant' does not exist.

### ISSUE THREAD

**Issue by akshaysyaduvanshi** [realm/SwiftLint#434]
when i try to run sonar-runner
it is giving me following error

ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
Caused by: The rule 'SwiftLint:legacy_constant' does not exist.

**Comment by jpsim** [comment]
Which version of SwiftLint do you have installed on this machine? The `legacy_constant` rule was originally included in SwiftLint 0.6.0: #357.
